# frozen_string_literal: true

source "https://rubygems.org"

gem 'sqlite3' #DBにSQLiteを使う
gem "sinatra-activerecord" #ActiveRecordを使用する
gem "rake" #効率的で簡単なタスクの実行を可能にする

# gem "rails"
gem 'sinatra' #Sinatraを使う
gem 'sinatra-contrib' #ヘルパーメソッドや拡張機能を提供する